AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Integrate Kinesis Data Stream with Lambda

Resources:
  MyKinesisDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 2
  
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Runtime: python3.9
      Handler: lambda_func.handler
      Tracing: Active
      Events:
        KinesisDataStream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt MyKinesisDataStream.Arn
            StartingPosition: LATEST
            BatchSize: 200
            
Outputs:
  MyKinesisDataStream:
    Description: Name of Kinesis Data Stream
    Value: !Ref MyKinesisDataStream
