AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventBridge to SNS Demo

Parameters:
  # Input SNS Topic ARN
  MySNSTopicArn:
    Type: String

Resources:
  # Define the event rule to filter for events
  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventBridge Event Rule"
      EventPattern:
        account:
          - !Sub '${AWS::AccountId}'
        source:
          - "aws.inspector"
      Targets:
        - Arn: !Ref MySNSTopicArn
          Id: "MySNStopic"

  # Grant permission to EventBridge to invoke SNS
  MyEventBridgeToSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sns:Publish
          Resource: !Ref MySNSTopicArn
      Topics:
        - !Ref MySNSTopicArn
